### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by Djiouvi** [bGrisafi/mesRecettes_back#1]
https://github.com/bGrisafi/mesRecettes_back/blob/137c025c6da9b35940c5aaf22e2e5a196ff91477/pom.xml#L44C16-L50C17

Je ne sais pas quel IDE tu utilises. 
Mais une bonne première chose que tu peux faire c'est sur ton shortcut de formatage de code avoir une règle qui s'y applique. 
Tu peux aller voir vers prettier.  

Après ça, selon ton IDE, tu peux ajouter une rule au commit de format ton code. Comme ça, si y'a un oubli, tu t'en fous. Pareil pour l'optimisation de tes imports. 

UPDATE : je vois que tu utilises VSCode.

**Comment by bGrisafi** [comment]
Oubli de mon coté, j'ai basculé sur Intellij (qui a donc prettier par défaut), j'ai juste pas eu le réflexe de l'utiliser après avoir mis ma dépendance, problem solved
